### PR TITLE
Hubert™️? Yes, hubert.

### PR DESCRIPTION
**Pull request by ghost**
this time I didn't mess up and I like added that funny icon thing in the browser tab and I added a Juan picture and I thanked Juan for Juan

### CODE REVIEW

**Comment by IAmThe2ndHuman** [comment]
impressionism

**Comment by ghost** [comment]
same

**Comment by IAmThe2ndHuman** [comment]
Duplicate of #

> j ukhoooooojuh ok`jouhk juoh [k`](juo khjouk hojukı 

- juk hjou khjoukıh

joukh joukhı

1. joukh joukhıjoku 

- [x] ljouk hjouk 

- [x] ıjokl ujo 
- [x] ıjoku 


- [ ] 

- [ ] koku  #@jokuıh joukıjo kuıjo ukhh

)

**Comment by ghost** [comment]
what

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by SuperchupuDev** [comment]
el

**Comment by ghost** [comment]
:SuperchupuCube:

**Review by Maxi2601 — APPROVED** [review]

**Comment by IAmThe2ndHuman** [comment]
34

**Comment by ghost** [comment]
31

**Pull request merged**
